# Generated by Django 5.0 on 2024-10-21 22:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
