# Generated by Django 5.0 on 2025-08-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_address_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
