# Generated by Django 5.0 on 2024-05-14 07:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_objectbase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, unique=True
            ),
        ),
    ]
