# Generated by Django 5.0 on 2024-06-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_address_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="additional_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="route_km_marker",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
