# Generated by Django 5.0 on 2024-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_address_additional_info_address_route_km_marker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="route_km_marker",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
