version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - ./envs/db.env

  app:
    container_name: appnasjod
    build: .
    volumes:
      - ./nasjod:/app
      - static_volume:/vol/web
    ports:
      - "9000:9000"
    depends_on:
      - db
    env_file:
      - ./envs/app.env

volumes:
  postgres_data_prod:
