# Generated by Django 5.0 on 2024-11-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="app_name",
            field=models.CharField(default="app-default", max_length=255),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
