# Generated by Django 5.0 on 2024-05-09 21:26

import core._helpers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Masjid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=20)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to=core._helpers.image_path_upload
                    ),
                ),
                ("cover", models.ImageField(upload_to="masjid_covers/")),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("parking", models.BooleanField(default=False)),
                ("disabled_access", models.BooleanField(default=False)),
                ("ablution_room", models.BooleanField(default=False)),
                ("woman_space", models.BooleanField(default=False)),
                ("adult_courses", models.BooleanField(default=False)),
                ("children_courses", models.BooleanField(default=False)),
                ("salat_al_eid", models.BooleanField(default=False)),
                ("salat_al_janaza", models.BooleanField(default=False)),
                ("iftar_ramadhan", models.BooleanField(default=False)),
                ("itikef", models.BooleanField(default=False)),
                (
                    "address",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="address_masjid",
                        to="core.address",
                    ),
                ),
            ],
        ),
    ]
