# Generated by Django 5.0 on 2024-05-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("masjid", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="masjid",
            options={"verbose_name_plural": "Masajid"},
        ),
    ]
