# Generated by Django 5.0 on 2024-10-21 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masjid", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="masjid",
            name="assistants",
            field=models.ManyToManyField(
                blank=True, related_name="assisted_masjids", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="masjid",
            name="imams",
            field=models.ManyToManyField(
                blank=True, related_name="led_masjids", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="masjid",
            name="managers",
            field=models.ManyToManyField(
                blank=True, related_name="managed_masjids", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="masjid",
            name="mousallis",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_masjids", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="masjid",
            name="prayer_times",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="masjid.masjid",
            ),
        ),
    ]
