# Generated by Django 5.0 on 2024-05-11 13:38

import core._helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masjid", "0002_alter_masjid_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masjid",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=core._helpers.image_path_upload
            ),
        ),
        migrations.AlterField(
            model_name="masjid",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
