# Generated by Django 5.0 on 2024-11-18 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_address_coordinates"),
        ("masjid", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestionMasjidModification",
            fields=[
                (
                    "objectbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.objectbase",
                    ),
                ),
            ],
            bases=("core.objectbase",),
        ),
    ]
