# Generated by Django 5.0 on 2024-05-31 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masjid", "0002_masjid_assistants_masjid_imams_masjid_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EidPrayerTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("eid_time", models.TimeField()),
                (
                    "masjid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eid_prayer_times",
                        to="masjid.masjid",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "eid_time"],
            },
        ),
        migrations.CreateModel(
            name="JumuahPrayerTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("jumuah_time", models.TimeField()),
                (
                    "masjid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jumuah_prayer_times",
                        to="masjid.masjid",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "jumuah_time"],
            },
        ),
        migrations.CreateModel(
            name="PrayerTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("fajr", models.TimeField()),
                ("sunrise", models.TimeField()),
                ("dhuhr", models.TimeField()),
                ("asr", models.TimeField()),
                ("maghrib", models.TimeField()),
                ("isha", models.TimeField()),
                (
                    "masjid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayer_times",
                        to="masjid.masjid",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddConstraint(
            model_name="eidprayertime",
            constraint=models.UniqueConstraint(
                fields=("masjid", "date", "eid_time"),
                name="unique_eid_time_per_day_per_masjid",
            ),
        ),
        migrations.AddConstraint(
            model_name="jumuahprayertime",
            constraint=models.UniqueConstraint(
                fields=("masjid", "date", "jumuah_time"),
                name="unique_jumuah_time_per_day_per_masjid",
            ),
        ),
        migrations.AddConstraint(
            model_name="prayertime",
            constraint=models.UniqueConstraint(
                fields=("masjid", "date"), name="unique_prayer_time_per_day_per_masjid"
            ),
        ),
    ]
