# Generated by Django 5.0 on 2024-06-05 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masjid", "0003_eidprayertime_jumuahprayertime_prayertime_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eidprayertime",
            options={},
        ),
        migrations.AlterModelOptions(
            name="jumuahprayertime",
            options={},
        ),
        migrations.AlterModelOptions(
            name="prayertime",
            options={},
        ),
        migrations.AddField(
            model_name="eidprayertime",
            name="hijri_date",
            field=models.CharField(default="", editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name="jumuahprayertime",
            name="hijri_date",
            field=models.CharField(default="", editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name="prayertime",
            name="hijri_date",
            field=models.CharField(default="", editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="eidprayertime",
            name="masjid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="masjid.masjid"
            ),
        ),
        migrations.AlterField(
            model_name="jumuahprayertime",
            name="masjid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="masjid.masjid"
            ),
        ),
        migrations.AlterField(
            model_name="prayertime",
            name="masjid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="masjid.masjid"
            ),
        ),
    ]
