# Generated by Django 5.0 on 2024-11-24 14:55

import core._helpers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_address_coordinates"),
        ("masjid", "0003_suggestionmasjidmodification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suggestionmasjidmodification",
            options={"verbose_name_plural": "SuggestionMasjidModifications"},
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="ablution_room",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="address_suggestion_masjid_modification",
                to="core.address",
            ),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="adult_courses",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="asr_iqama",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="children_courses",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=core._helpers.image_path_upload
            ),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="dhuhr_iqama",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="disabled_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="eid_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="fajr_iqama",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="first_timeslot_jumuah",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="iftar_ramadhan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="isha_iqama",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="itikef",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="jumuah_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="maghrib_iqama",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="message",
            field=models.CharField(
                blank=True,
                help_text="Optional message to provide additional information about the masjid modification suggestion.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="parking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=core._helpers.image_path_upload
            ),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="salat_al_eid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="salat_al_janaza",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="size",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="woman_space",
            field=models.BooleanField(default=False),
        ),
    ]
