# Generated by Django 5.0 on 2024-11-24 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masjid", "0004_alter_suggestionmasjidmodification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestionmasjidmodification",
            name="suggestion_masjid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions",
                to="masjid.masjid",
            ),
        ),
    ]
