# Generated by Django 5.0 on 2024-06-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masjid", "0004_alter_eidprayertime_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prayertime",
            options={"ordering": ["date"]},
        ),
        migrations.AddField(
            model_name="prayertime",
            name="asr_iqama",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prayertime",
            name="dhuhr_iqama",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prayertime",
            name="fajr_iqama",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prayertime",
            name="isha_iqama",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prayertime",
            name="maghrib_iqama",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
