# Generated by Django 5.0 on 2025-10-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masjid", "0005_suggestionmasjidmodification_suggestion_masjid"),
    ]

    operations = [
        migrations.AddField(
            model_name="masjid",
            name="name_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
