# Generated by Django 5.0 on 2024-08-30 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masjid", "0005_alter_prayertime_options_prayertime_asr_iqama_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prayertime",
            name="asr_iqama",
        ),
        migrations.RemoveField(
            model_name="prayertime",
            name="dhuhr_iqama",
        ),
        migrations.RemoveField(
            model_name="prayertime",
            name="fajr_iqama",
        ),
        migrations.RemoveField(
            model_name="prayertime",
            name="isha_iqama",
        ),
        migrations.RemoveField(
            model_name="prayertime",
            name="maghrib_iqama",
        ),
        migrations.RemoveField(
            model_name="prayertime",
            name="masjid",
        ),
        migrations.AddField(
            model_name="masjid",
            name="prayer_times",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="masjid.masjid",
            ),
        ),
        migrations.AddField(
            model_name="prayertime",
            name="masjids",
            field=models.ManyToManyField(blank=True, to="masjid.masjid"),
        ),
        migrations.AddField(
            model_name="prayertime",
            name="place",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
