# Generated by Django 5.0 on 2024-08-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("masjid", "0006_remove_prayertime_asr_iqama_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="prayertime",
            name="unique_prayer_time_per_day_per_masjid",
        ),
    ]
