# Generated by Django 5.0 on 2024-11-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("masjid", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contribution_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
    ]
