# Generated by Django 5.0 on 2024-11-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_usercontributor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercontributor",
            old_name="masjid",
            new_name="masjids",
        ),
    ]
