# Generated by Django 5.0 on 2024-11-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_masjid_usercontributor_masjids"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontributor",
            name="accept_to_display",
            field=models.BooleanField(default=False),
        ),
    ]
