# Generated by Django 5.0 on 2024-10-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("masjid", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EidPrayerTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hijri_date",
                    models.CharField(default="", editable=False, max_length=50),
                ),
                ("eid_time", models.TimeField()),
                (
                    "location",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.address",
                    ),
                ),
                ("masjids", models.ManyToManyField(blank=True, to="masjid.masjid")),
            ],
        ),
        migrations.CreateModel(
            name="IqamaTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hijri_date",
                    models.CharField(default="", editable=False, max_length=50),
                ),
                ("fajr_iqama", models.IntegerField(blank=True, null=True)),
                ("dhuhr_iqama", models.IntegerField(blank=True, null=True)),
                ("asr_iqama", models.IntegerField(blank=True, null=True)),
                ("maghrib_iqama", models.IntegerField(blank=True, null=True)),
                ("isha_iqama", models.IntegerField(blank=True, null=True)),
                (
                    "masjid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="masjid.masjid"
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JumuahPrayerTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hijri_date",
                    models.CharField(default="", editable=False, max_length=50),
                ),
                ("jumuah_time", models.TimeField()),
                (
                    "masjid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="masjid.masjid"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrayerTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hijri_date",
                    models.CharField(default="", editable=False, max_length=50),
                ),
                ("fajr", models.TimeField()),
                ("sunrise", models.TimeField()),
                ("dhuhr", models.TimeField()),
                ("asr", models.TimeField()),
                ("maghrib", models.TimeField()),
                ("isha", models.TimeField()),
                (
                    "location",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.address",
                    ),
                ),
                ("masjids", models.ManyToManyField(blank=True, to="masjid.masjid")),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddConstraint(
            model_name="eidprayertime",
            constraint=models.UniqueConstraint(
                fields=("date", "eid_time"), name="unique_eid_time_per_day_per_masjid"
            ),
        ),
        migrations.AddConstraint(
            model_name="jumuahprayertime",
            constraint=models.UniqueConstraint(
                fields=("masjid", "date", "jumuah_time"),
                name="unique_jumuah_time_per_day_per_masjid",
            ),
        ),
    ]
