# Generated by Django 5.0 on 2024-10-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_address_coordinates"),
        ("masjid", "0002_initial"),
        ("prayertime", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eidprayertime",
            name="unique_eid_time_per_day_per_masjid",
        ),
        migrations.AlterField(
            model_name="eidprayertime",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.address",
            ),
        ),
        migrations.AlterField(
            model_name="prayertime",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.address",
            ),
        ),
        migrations.AddConstraint(
            model_name="eidprayertime",
            constraint=models.UniqueConstraint(
                fields=("date", "eid_time"), name="unique_eid_time_per_day"
            ),
        ),
    ]
