# Generated by Django 5.0 on 2024-10-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prayertime",
            "0002_remove_eidprayertime_unique_eid_time_per_day_per_masjid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jumuahprayertime",
            name="first_timeslot_jumuah",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jumuahprayertime",
            name="jumuah_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
