# Generated by Django 5.0 on 2025-09-08 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masjid", "0005_suggestionmasjidmodification_suggestion_masjid"),
        ("prayertime", "0003_jumuahprayertime_first_timeslot_jumuah_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iqamatime",
            name="masjid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="iqamas",
                to="masjid.masjid",
            ),
        ),
        migrations.AlterField(
            model_name="jumuahprayertime",
            name="masjid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jumuah_prayer_times",
                to="masjid.masjid",
            ),
        ),
    ]
