# Generated by Django 5.0 on 2025-09-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayertime", "0004_alter_iqamatime_masjid_alter_jumuahprayertime_masjid"),
    ]

    operations = [
        migrations.AddField(
            model_name="iqamatime",
            name="dhuhr_iqama_from_asr",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
