# Generated by Django 5.0 on 2025-10-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayertime", "0005_iqamatime_dhuhr_iqama_from_asr"),
    ]

    operations = [
        migrations.AddField(
            model_name="iqamatime",
            name="dhuhr_iqama_hour",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
